import { randomUUID } from 'crypto';
import { coursePeriods } from "./course-periods";
import { courses } from "./courses";

const subjectsProps = {
  computingThinking: {
    id: randomUUID(),
    name: 'Pensamento Computacional',
    studyObjects: [
      '1.1 A EQUAÇÃO QUE REPRESENTA A ESSÊNCIA DOS COMPUTADORES',
      '1.2 O PROCESSO DE EXPLORAÇÃO DO POTENCIAL DOS COMPUTADORES ATRAVÉS DE CÓDIGOS E ALGORITMOS',
      '1.3 PRIMEIRO CONTATO COM CÓDIGOS DE COMPUTADORES',
      '2.1 SOFTWARE: CONCEITOS BÁSICOS',
      '2.2 SISTEMAS OPERACIONAIS E FIRMWARE',
      '2.3 LINGUAGENS DE PROGRAMAÇÃO',
      '3.1 HARDWARE DE COMPUTADOR',
      '3.2 UNIDADES DE ARMAZENAMENTO',
      '4.1 FUNDAMENTOS SOBRE PIXELS',
      '4.2 O ESQUEMA RGB DE REPRESENTAÇÃO DE CORES EM COMPUTADORES',
      '5.1 INSTRUÇÃO PARA MANIPULAÇÃO SIMPLES DE DADOS',
      '5.2 ESTRUTURA DE REPETIÇÃO FOR',
      '5.3 EXPRESSÕES',
      '5.4 ESTRUTURA CONDICIONAL',
      '6.1 PENSAMENTO COMPUTACIONAL E O PROFISSIONAL DO SÉCULO XXI',
      '6.2 APLICAÇÕES NA ECONOMIA CRIATIVA, NEGÓCIOS E CIÊNCIAS JURÍDICAS',
      '6.3 APLICAÇÕES NA EDUCAÇÃO E ENGENHARIA',
    ],
    periodId: coursePeriods.get(courses.computerScience)![0]?.id,
  },
  webDevelopment: {
    id: randomUUID(),
    name: 'Desenv. Web em Html5, Css, Javascript e Php',
    studyObjects: [
      '1.1 AMBIENTE WEB',
      '1.2 INTERFACE',
      '1.3 TECNOLOGIAS DO LADO CLIENTE',
      '1.4 TECNOLOGIAS DO LADO SERVIDOR',
      '2.1 ESTRUTURA DE PÁGINA WEB',
      '2.2 TAGS NA HTML',
      '2.3 TAGS COMPLEMENTARES',
      '2.4 FORMULÁRIO DE PÁGINA WEB',
      '3.1 FUNDAMENTOS DA CSS',
      '3.2 RECURSOS DA CSS3',
      '3.3 BOX MODEL, PSEUDOCLASSES, PSEUDOELEMENTOS E POSICIONAMENTO',
      '3.4 FRAMEWORKS CSS',
      '4.1 UTILIZAÇÃO DO JAVASCRIPT',
      '4.2 ESTRUTURAS DE DECISÃO E REPETIÇÃO',
      '4.3 VETOR EM JAVASCRIPT',
      '4.4 AJAX E JSON',
      '5.1 LINGUAGEM PHP',
      '5.2 ESTRUTURAS DE DECISÃO E REPETIÇÃO EM PHP',
      '5.3 VETORES E FUNÇÕES EM PHP',
      '6.1 CLASSE PDO',
      '6.2 MÉTODOS DA CLASSE PDO',
      '6.3 APLICAÇÃO COM HTML E PHP',
    ],
    periodId: coursePeriods.get(courses.computerScience)![0]?.id,
  },
  computersArchitecture: {
    id: randomUUID(),
    name: 'Arquitetura de Computadores',
    studyObjects: [
      '1.1 A EVOLUÇÃO HISTÓRICA DOS COMPUTADORES',
      '1.2 OS COMPONENTES DE UM SISTEMA COMPUTACIONAL',
      '1.3 O PAPEL DO SISTEMA OPERACIONAL NOS COMPUTADORES',
      '1.4 A IMPORTÂNCIA DA COMUNICAÇÃO EM REDE COM OS SISTEMAS COMPUTACIONAIS',
      '2.1 A ESTRUTURA BÁSICA DE UM COMPUTADOR',
      '2.2 OS PRINCÍPIOS BÁSICOS DOS SUBSISTEMAS DE PROCESSAMENTO',
      '2.3 O ESSENCIAL SOBRE O SISTEMA OPERACIONAL',
      '3.1 AS UNIDADES DE INFORMAÇÃO UTILIZADAS PELOS SISTEMAS DE COMPUTAÇÃO',
      '3.2 OS SISTEMAS DE NUMERAÇÃO A PARTIR DA PRÁTICA DE OPERAÇÕES ARITMÉTICAS',
      '3.3 A CONVERSÃO ENTRE OS SISTEMAS DE NUMERAÇÃO',
      '3.4 AS TABELAS DE REPRESENTAÇÃO DE DADOS',
      '4.1 AS OPERAÇÕES BÁSICAS DA ÁLGEBRA BOOLEANA',
      '4.2 PORTAS LÓGICAS, OPERAÇÕES LÓGICAS E AS SUAS TABELAS VERDADE',
      '4.3 AS EXPRESSÕES LÓGICAS E DIAGRAMAS LÓGICOS',
      '5.1 AS VANTAGENS DA COMPUTAÇÃO DE ALTO DESEMPENHO',
      '5.2 OS TIPOS DE ORGANIZAÇÕES DE PROCESSADORES PARALELOS',
      '5.3 AS QUESTÕES DE DESEMPENHO DO HARDWARE QUE DIRECIONAM O MOVIMENTO PARA OS COMPUTADORES MULTICORE',
      '6.1 IDENTIFICAR CARACTERÍSTICAS E PROPRIEDADES DA ARQUITETURA CISC',
      '6.2 IDENTIFICAR CARACTERÍSTICAS E PROPRIEDADES DA ARQUITETURA RISC',
    ],
    periodId: coursePeriods.get(courses.computerScience)![0]?.id,
  },
  quantitativeMethods: {
    id: randomUUID(),
    name: "Métodos Quantitativos",
    studyObjects: [
      "1.1 CONCEITOS GERAIS DE PESQUISA OPERACIONAL E SUA IMPORTÂNCIA NO PROCESSO DE TOMADA DE DECISÃO",
      "1.2 AS PRINCIPAIS CARACTERÍSTICAS E PROPRIEDADES DE UM MODELO DE PROGRAMAÇÃO LINEAR",
      "1.3 O MÉTODO GRÁFICO PARA A SOLUÇÃO DE PROBLEMAS DE PROGRAMAÇÃO LINEAR",
      "2.1 A TÉCNICA DE MODELAGEM EM PROBLEMAS CLÁSSICOS DE PROGRAMAÇÃO LINEAR",
      "2.2 A TÉCNICA DE MODELAGEM NOS PROBLEMAS DE TRANSPORTE E TRANSBORDO",
      "2.3 A TÉCNICA DE MODELAGEM EM PROBLEMAS DE ALOCAÇÃO",
      "3.1 APLICAR A DUALIDADE PARA SOLUÇÃO DE PROBLEMAS DE PROGRAMAÇÃO LINEAR",
      "3.2 AVALIAR A SENSIBILIDADE DA SOLUÇÃO OBTIDA PARA PROBLEMAS DE PROGRAMAÇÃO LINEAR EM RELAÇÃO À INCERTEZA OU ERROS DE ESTIMATIVA QUANTO AOS COEFICIENTES DO MODELO",
      "4.1 EMPREGAR O MÉTODO SIMPLEX PARA A SOLUÇÃO DE PROBLEMAS DE PROGRAMAÇÃO LINEAR",
      "4.2 APLICAR O SOLVER PARA SOLUÇÃO DE PROBLEMAS DE PROGRAMAÇÃO LINEAR",
    ],
    periodId: coursePeriods.get(courses.computerScience)![3]?.id,
  },
  calculus: {
    id: randomUUID(),
    name: "Cálculo Diferencial e Integral",
    studyObjects: [
      "1.1 LIMITE DE UMA FUNÇÃO REAL",
      "1.2 CÁLCULO DO LIMITE DE UMA FUNÇÃO REAL",
      "1.3 CONTINUIDADE DA FUNÇÃO E ASSÍNTOTAS",
      "2.1 DERIVADA DE UMA FUNÇÃO REAL",
      "2.2 CÁLCULO DE DERIVADA",
      "2.3 REGRA DA CADEIA",
      "2.4 DERIVADA DE ORDENS SUPERIORES",
      "3.1 RETA TANGENTE E NORMAL",
      "3.2 TAXAS DE VARIAÇÃO",
      "3.3 DERIVADA NO ESTUDO DE FUNÇÕES",
      "3.4 PROBLEMAS DE OTIMIZAÇÃO",
      "4.1 INTEGRAL DE UMA FUNÇÃO REAL",
      "4.2 INTEGRAÇÃO POR SUBSTITUIÇÃO",
      "4.3 INTEGRAÇÃO POR PARTES",
      "4.4 INTEGRAÇÃO POR FRAÇÕES PARCIAIS",
      "5.1 ARCOS DE CURVA",
      "5.2 CÁLCULO DE ÁREAS",
      "5.3 CÁLCULO DE VOLUMES",
    ],
    periodId: coursePeriods.get(courses.computerScience)![3]?.id,
  },
  operationalSystems: {
    id: randomUUID(),
    name: "Sistemas Operacionais",
    studyObjects: [
      "1.1 EVOLUÇÃO DOS SISTEMAS OPERACIONAIS",
      "1.2 TIPOS DE SISTEMAS OPERACIONAIS",
      "1.3 ESTRUTURA DO SISTEMA OPERACIONAL",
      "1.4 LINUX BÁSICO",
      "2.1 CONCEITOS DE PROCESSO",
      "2.2 PROGRAMAS CONCORRENTES",
      "2.3 COMUNICAÇÃO ENTRE PROCESSOS",
      "2.4 ESCALONAMENTO",
      "3.1 CONCEITOS E GESTÃO DE MEMÓRIA",
      "3.2 POLÍTICAS DE ALOCAÇÃO DE MEMÓRIA",
      "3.3 MEMÓRIA VIRTUAL",
      "3.4 LINUX E MEMÓRIA",
      "4.1 IMPLEMENTAÇÃO",
      "4.2 CONCEITOS",
      "4.3 FERRAMENTAS PARA ARQUIVOS DO LINUX",
      "4.4 EDITORES DE ARQUIVOS LINUX",
      "5.1 FERRAMENTA CRON",
      "5.2 SCRIPTS PARA AUTOMATIZAÇÃO DE TAREFAS",
      "5.3 VARIÁVEIS DE AMBIENTE E ESTRUTURA DE DECISÃO EM SCRIPTS",
      "5.4 ESTRUTURA DE REPETIÇÃO EM SCRIPTS",
    ],
    periodId: coursePeriods.get(courses.computerScience)![3]?.id,
  },
  basicSoftwareProgrammingC: {
    id: randomUUID(),
    name: "Programação de Software Básico em C",
    studyObjects: [
      "1.1 Linguagem C na programação de sistemas",
      "1.2 Bibliotecas para datas, horários e gráficos",
      "1.3 API OpenGL",
      "1.4 Eventos de teclado e mouse",
      "2.1 Entrada e saída pelo console",
      "2.2 Padronização do C",
      "2.3 Entrada e saída por arquivos",
      "3.1 Porta serial e portas de microcontroladores",
      "3.2 Controle de dispositivos e aquisição de dados com microcontroladores",
      "3.3 Sockets e cliente/servidor TCP e UDP",
      "3.4 Cliente/servidor HTTP e cliente MQTT para IoT",
      "4.1 Criação de processos com fork",
      "4.2 Funções para threads básicos",
      "4.3 Sincronização de threads",
    ],
    periodId: coursePeriods.get(courses.computerScience)![3]?.id,
  },
  computerNetworkProtocols: {
    id: randomUUID(),
    name: "Protocolos de Redes de Computadores",
    studyObjects: [
      "1.1 OS PROTOCOLOS DE APLICAÇÃO HTTP, FTP E TELNET",
      "1.2 OS PRINCIPAIS PROTOCOLOS DE APLICAÇÃO RELACIONADOS AO SERVIÇO DE CORREIO ELETRÔNICO",
      "1.3 OS PROTOCOLOS DE APLICAÇÃO DNS, DHCP E SNMP",
      "1.4 FERRAMENTAS E TÉCNICAS PARA MONITORAR O FUNCIONAMENTO DOS PROTOCOLOS ESTUDADOS, COM INTERPRETAÇÃO DOS RESULTADOS",
      "2.1 OS SERVIÇOS OFERECIDOS PELA CAMADA DE TRANSPORTE",
      "2.2 A TRANSFERÊNCIA DE DADOS FIM A FIM",
      "2.3 OS PROTOCOLOS DE TRANSPORTE DA INTERNET",
      "2.4 PROTOCOLOS DA CAMADA DE TRANSPORTE",
      "3.1 AS CARACTERÍSTICAS DO PAYLOAD E DO ENDEREÇAMENTO IPV4",
      "3.2 O ENDEREÇAMENTO DE REDES E SUB­REDES IPV4",
      "3.3 AS SOLUÇÕES TEMPORÁRIAS PARA SANAR O ESGOTAMENTO DO ENDEREÇAMENTO IPV4",
      "3.4 FERRAMENTAS DE ANÁLISE E TROUBLESHOOTING DO IPV4 E SEUS PROTOCOLOS AUXILIARES",
      "4.1 AS CARACTERÍSTICAS DO PAYLOAD E ENDEREÇAMENTO IPV6",
      "4.2 O ENDEREÇAMENTO DE REDES E SUB­REDES IPV6",
      "4.3 AS SOLUÇÕES DE INTEGRAÇÃO ENTRE O IPV4 E O IPV6",
      "4.4 AS FUNCIONALIDADES DO PROTOCOLO ICMPV6",
    ],
    periodId: coursePeriods.get(courses.computerScience)![3]?.id,
  },
  programmingParadigms: {
    id: randomUUID(),
    name: 'Paradigmas de Ling. de Programação com Python',
    studyObjects: [
      '1.1 LINGUAGENS DE PROGRAMAÇÃO',
      '1.2 CRITÉRIOS DE AVALIAÇÃO DE LINGUAGENS DE PROGRAMAÇÃO',
      '1.3 PARADIAGMAS DE LINGUAGEM DE PROGRAMAÇÃO',
      '1.4 MÉTODOS DE IMPLEMENTAÇÃO DAS LINGUAGENS DE PROGRAMAÇÃO',
      '2.1 LINGUAGEM PYTHON E SUAS CARACTERÍSTICAS',
      '2.2 VARIÁVEIS EM PYTHON',
      '2.3 TIPOS DE DADOS E EXPRESSÕES EM PYTHON',
      '2.4 ATRIBUIÇÃO, ENTRADA E SAÍDA DE DADOS EM PYTHON',
      '3.1 DECISÃO E REPETIÇÃO EM PYTHON',
      '3.2 ESTRUTURAS DE DADOS EM PYTHON',
      '3.3 PROGRAMAÇÃO ORIENTADA A OBJETOS EM PYTHON',
      '3.4 PROGRAMAÇÃO FUNCIONAL EM PYTHON',
      '4.1 MÉTODOS E FUNÇÕES EM PYTHON',
      '4.2 MÓDULOS E PACOTES EM PYTHON',
      '4.3 TRATAMENTO DE ERROS EM PYTHON',
      '4.4 PROGRAMAÇÃO ORIENTADA A OBJETOS COM PYTHON',
      '5.1 INTERFACES GRÁFICAS EM PYTHON',
      '5.2 PROGRAMAÇÃO PARA WEB EM PYTHON',
      '5.3 ACESSO A BANCO DE DADOS EM PYTHON',
      '5.4 PROGRAMAÇÃO DISTRIBUÍDA EM PYTHON',
    ],
    periodId: coursePeriods.get(courses.computerScience)![1]?.id,
  },
  dataStructures: {
    id: randomUUID(),
    name: 'Estruturas de Dados',
    studyObjects: [
      '1.1 TIPOS ABSTRATOS DE DADOS',
      '1.2 ESTRUTURAS DE DADOS LINEARES',
      '1.3 PILHAS',
      '1.4 FILAS',
      '2.1 LISTAS LIGADAS',
      '2.2 LISTAS DUPLAMENTE LIGADAS',
      '2.3 LISTAS CIRCULARES',
      '2.4 APLICAÇÕES DE LISTAS',
      '3.1 ÁRVORES BINÁRIAS',
      '3.2 ÁRVORES DE BUSCA BINÁRIA',
      '3.3 ÁRVORES BALANCEADAS',
      '3.4 OPERAÇÕES EM ÁRVORES',
      '4.1 CONCEITOS DE GRAFOS',
      '4.2 REPRESENTAÇÃO DE GRAFOS',
      '4.3 BUSCA EM GRAFOS',
      '4.4 ALGORITMOS EM GRAFOS',
      '5.1 ALGORITMOS DE ORDENAÇÃO',
      '5.2 ALGORITMOS DE BUSCA',
      '5.3 ANÁLISE DE COMPLEXIDADE',
      '5.4 HASH E TABELAS DE DISPERSÃO',
    ],
    periodId: coursePeriods.get(courses.computerScience)![1]?.id,
  },
  databases: {
    id: randomUUID(),
    name: 'Banco de Dados',
    studyObjects: [
      '1.1 CONCEITOS FUNDAMENTAIS DE BANCO DE DADOS',
      '1.2 MODELO ENTIDADE-RELACIONAMENTO',
      '1.3 NORMALIZAÇÃO DE DADOS',
      '1.4 SGBD E SUAS CARACTERÍSTICAS',
      '2.1 LINGUAGEM SQL - DEFINIÇÃO DE DADOS',
      '2.2 LINGUAGEM SQL - MANIPULAÇÃO DE DADOS',
      '2.3 LINGUAGEM SQL - CONSULTAS',
      '2.4 LINGUAGEM SQL - FUNÇÕES E PROCEDURES',
      '3.1 TRANSAÇÕES E CONTROLE DE CONCORRÊNCIA',
      '3.2 BACKUP E RECUPERAÇÃO',
      '3.3 SEGURANÇA EM BANCO DE DADOS',
      '3.4 OTIMIZAÇÃO DE CONSULTAS',
      '4.1 BANCOS DE DADOS DISTRIBUÍDOS',
      '4.2 DATA WAREHOUSE',
      '4.3 BANCOS DE DADOS NOSQL',
      '4.4 BIG DATA E ANÁLISE DE DADOS',
    ],
    periodId: coursePeriods.get(courses.computerScience)![1]?.id,
  },
  softwareEngineering: {
    id: randomUUID(),
    name: 'Engenharia de Software',
    studyObjects: [
      '1.1 CONCEITOS FUNDAMENTAIS DE ENGENHARIA DE SOFTWARE',
      '1.2 CICLO DE VIDA DO SOFTWARE',
      '1.3 MODELOS DE PROCESSO DE SOFTWARE',
      '1.4 GERENCIAMENTO DE PROJETOS DE SOFTWARE',
      '2.1 ANÁLISE E ESPECIFICAÇÃO DE REQUISITOS',
      '2.2 TÉCNICAS DE LEVANTAMENTO DE REQUISITOS',
      '2.3 DOCUMENTAÇÃO DE REQUISITOS',
      '2.4 VALIDAÇÃO E VERIFICAÇÃO DE REQUISITOS',
      '3.1 PROJETO DE SOFTWARE',
      '3.2 ARQUITETURA DE SOFTWARE',
      '3.3 PADRÕES DE PROJETO',
      '3.4 PROJETO DE INTERFACE',
      '4.1 IMPLEMENTAÇÃO E CODIFICAÇÃO',
      '4.2 TESTES DE SOFTWARE',
      '4.3 MANUTENÇÃO DE SOFTWARE',
      '4.4 QUALIDADE DE SOFTWARE',
      '5.1 METODOLOGIAS ÁGEIS',
      '5.2 SCRUM E KANBAN',
      '5.3 INTEGRAÇÃO CONTÍNUA',
      '5.4 DEVOPS E DEPLOYMENT',
    ],
    periodId: coursePeriods.get(courses.computerScience)![2]?.id,
  },
  math: {
    id: randomUUID(),
    name: 'Matemática',
    studyObjects: [
      '1.1 NÚMEROS REAIS',
      '1.2 FUNÇÕES',
      '1.3 FUNÇÃO AFIM',
      '1.4 FUNÇÃO QUADRÁTICA',
      '2.1 FUNÇÃO EXPONENCIAL',
      '2.2 FUNÇÃO LOGARÍTMICA',
      '2.3 PROGRESSÕES ARITMÉTICAS',
      '2.4 PROGRESSÕES GEOMÉTRICAS',
      '3.1 TRIGONOMETRIA',
      '3.2 MATRIZES',
      '3.3 DETERMINANTES',
      '3.4 SISTEMAS LINEARES',
      '4.1 ANÁLISE COMBINATÓRIA',
      '4.2 PROBABILIDADE',
      '4.3 ESTATÍSTICA DESCRITIVA',
      '4.4 ESTATÍSTICA INFERENCIAL',
    ],
    periodId: coursePeriods.get(courses.computerScience)![0]?.id,
  },
  securityIntroduction: {
    id: randomUUID(),
    name: 'Introdução à Segurança da Informação',
    studyObjects: [
      '1.1 CONCEITOS FUNDAMENTAIS DE SEGURANÇA DA INFORMAÇÃO',
      '1.2 PRINCÍPIOS DA SEGURANÇA DA INFORMAÇÃO',
      '1.3 AMEAÇAS E VULNERABILIDADES',
      '1.4 ANÁLISE DE RISCOS',
      '2.1 CRIPTOGRAFIA E CRIPTOLOGIA',
      '2.2 SISTEMAS DE CRIPTOGRAFIA SIMÉTRICA',
      '2.3 SISTEMAS DE CRIPTOGRAFIA ASSIMÉTRICA',
      '2.4 FUNÇÕES HASH E ASSINATURA DIGITAL',
      '3.1 CONTROLE DE ACESSO',
      '3.2 AUTENTICAÇÃO E AUTORIZAÇÃO',
      '3.3 AUDITORIA E MONITORAMENTO',
      '3.4 POLÍTICAS DE SEGURANÇA',
      '4.1 SEGURANÇA EM REDES',
      '4.2 FIREWALLS E SISTEMAS DE DETECÇÃO',
      '4.3 SEGURANÇA EM SISTEMAS OPERACIONAIS',
      '4.4 SEGURANÇA EM APLICAÇÕES WEB',
    ],
    periodId: coursePeriods.get(courses.cybersecurity)![0]?.id,
  },
  computerNetworksFundamentals: {
    id: randomUUID(),
    name: 'Fundamentos de Redes de Computadores',
    studyObjects: [
      '1.1 CONCEITOS BÁSICOS DE REDES',
      '1.2 TOPOLOGIAS DE REDES',
      '1.3 MODELO OSI',
      '1.4 MODELO TCP/IP',
      '2.1 CAMADA FÍSICA',
      '2.2 CAMADA DE ENLACE',
      '2.3 PROTOCOLOS DE ENLACE',
      '2.4 SWITCHING',
      '3.1 CAMADA DE REDE',
      '3.2 PROTOCOLO IP',
      '3.3 ROTEAMENTO',
      '3.4 ICMP E ARP',
      '4.1 CAMADA DE TRANSPORTE',
      '4.2 PROTOCOLO TCP',
      '4.3 PROTOCOLO UDP',
      '4.4 CONTROLE DE CONGESTIONAMENTO',
      '5.1 CAMADA DE APLICAÇÃO',
      '5.2 PROTOCOLOS DE APLICAÇÃO',
      '5.3 SERVIÇOS DE REDE',
      '5.4 SEGURANÇA EM REDES',
    ],
    periodId: coursePeriods.get(courses.computerScience)![2]?.id,
  },
};

export const subjects = subjectsProps;
